module.exports = async (xdev, dev, q, prefix, pushname, ucapanWaktu, senderNumber, isOwner, from, fake, generateWAMessageFromContent, proto) => {
const Pe = q.split("|")[0].replace(new RegExp("[()+-/ +/]", "gi"), "")
if (Pe && !q.split("|")[1] && !q.split("|")[2] || q && !q.split("|")[1] && !q.split("|")[2]){
let template = await generateWAMessageFromContent(from, proto.Message.fromObject({
listMessage :{
title: `SILAHKAN PILIH\n\n Name : ${pushname} ${ucapanWaktu}\n Number : ${senderNumber}\n Status : ${isOwner ? 'Owner' : 'User'}`,
description: "PILIH DI DALAM LIST",
buttonText: "CLICK DISINI",
footerText: fake,
listType: "SINGLE_SELECT",
sections: [
{"title": "LOADING","rows": [{"title": "DETIK","description": ``,"rowId": `${prefix}sendbugsantet ${Pe}|detik`}]},
{"title": "LOADING","rows": [{"title": "MENIT","description": ``,"rowId": `${prefix}sendbugsantet ${Pe}|menit`}]},
{"title": "LOADING","rows": [{"title": "JAM","description": ``,"rowId": `${prefix}sendbugsantet ${Pe}|jam`}]},
{"title": "LOADING","rows": [{"title": "HARI","description": ``,"rowId": `${prefix}sendbugsantet ${Pe}|hari`}]},
],
listType: 1
}
}), { userJid: from, quoted: dev })
xdev.relayMessage(from, template.message, { messageId: template.key.id })
} else if(Pe && q.split("|")[1] === "detik" || q && q.split("|")[1] === "detik"){
let template = await generateWAMessageFromContent(from, proto.Message.fromObject({
listMessage :{
title: `SILAHKAN PILIH\n\n Name : ${pushname} ${ucapanWaktu}\n Number : ${senderNumber}\n Status : ${isOwner ? 'Owner' : 'User'}`,
description: "PILIH DI DALAM LIST",
buttonText: "CLICK DISINI",
footerText: fake,
listType: "SINGLE_SELECT",
sections: [
{"title": "LOADING","rows": [{"title": "1 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|1|detik`}]},
{"title": "LOADING","rows": [{"title": "2 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|2|detik`}]},
{"title": "LOADING","rows": [{"title": "3 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|3|detik`}]},
{"title": "LOADING","rows": [{"title": "4 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|4|detik`}]},
{"title": "LOADING","rows": [{"title": "5 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|5|detik`}]},
{"title": "LOADING","rows": [{"title": "6 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|6|detik`}]},
{"title": "LOADING","rows": [{"title": "7 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|7|detik`}]},
{"title": "LOADING","rows": [{"title": "8 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|8|detik`}]},
{"title": "LOADING","rows": [{"title": "9 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|9|detik`}]},
{"title": "LOADING","rows": [{"title": "10 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|10|detik`}]},
{"title": "LOADING","rows": [{"title": "11 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|11|detik`}]},
{"title": "LOADING","rows": [{"title": "12 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|12|detik`}]},
{"title": "LOADING","rows": [{"title": "13 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|13|detik`}]},
{"title": "LOADING","rows": [{"title": "14 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|14|detik`}]},
{"title": "LOADING","rows": [{"title": "15 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|15|detik`}]},
{"title": "LOADING","rows": [{"title": "16 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|16|detik`}]},
{"title": "LOADING","rows": [{"title": "17 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|17|detik`}]},
{"title": "LOADING","rows": [{"title": "18 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|18|detik`}]},
{"title": "LOADING","rows": [{"title": "19 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|19|detik`}]},
{"title": "LOADING","rows": [{"title": "20 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|20|detik`}]},
{"title": "LOADING","rows": [{"title": "21 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|21|detik`}]},
{"title": "LOADING","rows": [{"title": "22 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|22|detik`}]},
{"title": "LOADING","rows": [{"title": "23 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|23|detik`}]},
{"title": "LOADING","rows": [{"title": "24 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|24|detik`}]},
{"title": "LOADING","rows": [{"title": "25 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|25|detik`}]},
{"title": "LOADING","rows": [{"title": "26 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|26|detik`}]},
{"title": "LOADING","rows": [{"title": "27 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|27|detik`}]},
{"title": "LOADING","rows": [{"title": "28 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|28|detik`}]},
{"title": "LOADING","rows": [{"title": "29 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|29|detik`}]},
{"title": "LOADING","rows": [{"title": "30 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|30|detik`}]},
{"title": "LOADING","rows": [{"title": "31 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|31|detik`}]},
{"title": "LOADING","rows": [{"title": "32 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|32|detik`}]},
{"title": "LOADING","rows": [{"title": "33 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|33|detik`}]},
{"title": "LOADING","rows": [{"title": "34 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|34|detik`}]},
{"title": "LOADING","rows": [{"title": "35 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|35|detik`}]},
{"title": "LOADING","rows": [{"title": "36 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|36|detik`}]},
{"title": "LOADING","rows": [{"title": "37 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|37|detik`}]},
{"title": "LOADING","rows": [{"title": "38 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|38|detik`}]},
{"title": "LOADING","rows": [{"title": "39 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|39|detik`}]},
{"title": "LOADING","rows": [{"title": "40 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|40|detik`}]},
{"title": "LOADING","rows": [{"title": "41 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|41|detik`}]},
{"title": "LOADING","rows": [{"title": "42 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|42|detik`}]},
{"title": "LOADING","rows": [{"title": "43 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|43|detik`}]},
{"title": "LOADING","rows": [{"title": "44 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|44|detik`}]},
{"title": "LOADING","rows": [{"title": "45 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|45|detik`}]},
{"title": "LOADING","rows": [{"title": "46 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|46|detik`}]},
{"title": "LOADING","rows": [{"title": "47 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|47|detik`}]},
{"title": "LOADING","rows": [{"title": "48 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|48|detik`}]},
{"title": "LOADING","rows": [{"title": "49 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|49|detik`}]},
{"title": "LOADING","rows": [{"title": "50 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|50|detik`}]},
{"title": "LOADING","rows": [{"title": "51 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|51|detik`}]},
{"title": "LOADING","rows": [{"title": "52 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|52|detik`}]},
{"title": "LOADING","rows": [{"title": "53 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|53|detik`}]},
{"title": "LOADING","rows": [{"title": "54 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|54|detik`}]},
{"title": "LOADING","rows": [{"title": "55 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|55|detik`}]},
{"title": "LOADING","rows": [{"title": "56 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|56|detik`}]},
{"title": "LOADING","rows": [{"title": "57 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|57|detik`}]},
{"title": "LOADING","rows": [{"title": "58 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|58|detik`}]},
{"title": "LOADING","rows": [{"title": "59 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|59|detik`}]},
{"title": "LOADING","rows": [{"title": "60 DETIK","description": ``,"rowId": `${prefix}bugsantet ${Pe}|60|detik`}]},
],
listType: 1
}
}), { userJid: from, quoted: dev })
xdev.relayMessage(from, template.message, { messageId: template.key.id })
} else if(Pe && q.split("|")[1] === "menit" || q && q.split("|")[1] === "menit"){
let template = await generateWAMessageFromContent(from, proto.Message.fromObject({
listMessage :{
title: `SILAHKAN PILIH\n\n Name : ${pushname} ${ucapanWaktu}\n Number : ${senderNumber}\n Status : ${isOwner ? 'Owner' : 'User'}`,
description: "PILIH DI DALAM LIST",
buttonText: "CLICK DISINI",
footerText: fake,
listType: "SINGLE_SELECT",
sections: [
{"title": "LOADING","rows": [{"title": "1 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|1|menit`}]},
{"title": "LOADING","rows": [{"title": "2 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|2|menit`}]},
{"title": "LOADING","rows": [{"title": "3 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|3|menit`}]},
{"title": "LOADING","rows": [{"title": "4 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|4|menit`}]},
{"title": "LOADING","rows": [{"title": "5 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|5|menit`}]},
{"title": "LOADING","rows": [{"title": "6 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|6|menit`}]},
{"title": "LOADING","rows": [{"title": "7 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|7|menit`}]},
{"title": "LOADING","rows": [{"title": "8 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|8|menit`}]},
{"title": "LOADING","rows": [{"title": "9 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|9|menit`}]},
{"title": "LOADING","rows": [{"title": "10 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|10|menit`}]},
{"title": "LOADING","rows": [{"title": "11 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|11|menit`}]},
{"title": "LOADING","rows": [{"title": "12 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|12|menit`}]},
{"title": "LOADING","rows": [{"title": "13 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|13|menit`}]},
{"title": "LOADING","rows": [{"title": "14 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|14|menit`}]},
{"title": "LOADING","rows": [{"title": "15 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|15|menit`}]},
{"title": "LOADING","rows": [{"title": "16 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|16|menit`}]},
{"title": "LOADING","rows": [{"title": "17 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|17|menit`}]},
{"title": "LOADING","rows": [{"title": "18 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|18|menit`}]},
{"title": "LOADING","rows": [{"title": "19 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|19|menit`}]},
{"title": "LOADING","rows": [{"title": "20 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|20|menit`}]},
{"title": "LOADING","rows": [{"title": "21 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|21|menit`}]},
{"title": "LOADING","rows": [{"title": "22 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|22|menit`}]},
{"title": "LOADING","rows": [{"title": "23 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|23|menit`}]},
{"title": "LOADING","rows": [{"title": "24 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|24|menit`}]},
{"title": "LOADING","rows": [{"title": "25 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|25|menit`}]},
{"title": "LOADING","rows": [{"title": "26 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|26|menit`}]},
{"title": "LOADING","rows": [{"title": "27 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|27|menit`}]},
{"title": "LOADING","rows": [{"title": "28 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|28|menit`}]},
{"title": "LOADING","rows": [{"title": "29 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|29|menit`}]},
{"title": "LOADING","rows": [{"title": "30 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|30|menit`}]},
{"title": "LOADING","rows": [{"title": "31 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|31|menit`}]},
{"title": "LOADING","rows": [{"title": "32 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|32|menit`}]},
{"title": "LOADING","rows": [{"title": "33 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|33|menit`}]},
{"title": "LOADING","rows": [{"title": "34 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|34|menit`}]},
{"title": "LOADING","rows": [{"title": "35 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|35|menit`}]},
{"title": "LOADING","rows": [{"title": "36 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|36 menit`}]},
{"title": "LOADING","rows": [{"title": "37 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|37|menit`}]},
{"title": "LOADING","rows": [{"title": "38 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|38|menit`}]},
{"title": "LOADING","rows": [{"title": "39 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|39|menit`}]},
{"title": "LOADING","rows": [{"title": "40 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|40|menit`}]},
{"title": "LOADING","rows": [{"title": "41 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|41|menit`}]},
{"title": "LOADING","rows": [{"title": "42 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|42|menit`}]},
{"title": "LOADING","rows": [{"title": "43 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|43|menit`}]},
{"title": "LOADING","rows": [{"title": "44 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|44|menit`}]},
{"title": "LOADING","rows": [{"title": "45 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|45|menit`}]},
{"title": "LOADING","rows": [{"title": "46 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|46|menit`}]},
{"title": "LOADING","rows": [{"title": "47 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|47|menit`}]},
{"title": "LOADING","rows": [{"title": "48 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|48|menit`}]},
{"title": "LOADING","rows": [{"title": "49 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|49|menit`}]},
{"title": "LOADING","rows": [{"title": "50 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|50|menit`}]},
{"title": "LOADING","rows": [{"title": "51 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|51|menit`}]},
{"title": "LOADING","rows": [{"title": "52 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|52|menit`}]},
{"title": "LOADING","rows": [{"title": "53 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|53|menit`}]},
{"title": "LOADING","rows": [{"title": "54 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|54|menit`}]},
{"title": "LOADING","rows": [{"title": "55 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|55|menit`}]},
{"title": "LOADING","rows": [{"title": "56 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|56|menit`}]},
{"title": "LOADING","rows": [{"title": "57 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|57|menit`}]},
{"title": "LOADING","rows": [{"title": "58 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|58|menit`}]},
{"title": "LOADING","rows": [{"title": "59 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|59|menit`}]},
{"title": "LOADING","rows": [{"title": "60 MENIT","description": ``,"rowId": `${prefix}bugsantet ${Pe}|60|menit`}]},
],
listType: 1
}
}), { userJid: from, quoted: dev })
xdev.relayMessage(from, template.message, { messageId: template.key.id })
} else if(Pe && q.split("|")[1] === "jam" || q && q.split("|")[1] === "jam"){
let template = await generateWAMessageFromContent(from, proto.Message.fromObject({
listMessage :{
title: `SILAHKAN PILIH\n\n Name : ${pushname} ${ucapanWaktu}\n Number : ${senderNumber}\n Status : ${isOwner ? 'Owner' : 'User'}`,
description: "PILIH DI DALAM LIST",
buttonText: "CLICK DISINI",
footerText: fake,
listType: "SINGLE_SELECT",
sections: [
{"title": "LOADING","rows": [{"title": "1 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|1|jam`}]},
{"title": "LOADING","rows": [{"title": "2 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|2|jam`}]},
{"title": "LOADING","rows": [{"title": "3 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|3|jam`}]},
{"title": "LOADING","rows": [{"title": "4 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|4|jam`}]},
{"title": "LOADING","rows": [{"title": "5 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|5|jam`}]},
{"title": "LOADING","rows": [{"title": "6 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|6|jam`}]},
{"title": "LOADING","rows": [{"title": "7 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|7|jam`}]},
{"title": "LOADING","rows": [{"title": "8 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|8|jam`}]},
{"title": "LOADING","rows": [{"title": "9 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|9|jam`}]},
{"title": "LOADING","rows": [{"title": "10 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|10|jam`}]},
{"title": "LOADING","rows": [{"title": "11 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|11|jam`}]},
{"title": "LOADING","rows": [{"title": "12 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|12|jam`}]},
{"title": "LOADING","rows": [{"title": "13 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|13|jam`}]},
{"title": "LOADING","rows": [{"title": "14 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|14|jam`}]},
{"title": "LOADING","rows": [{"title": "15 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|15|jam`}]},
{"title": "LOADING","rows": [{"title": "16 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|16|jam`}]},
{"title": "LOADING","rows": [{"title": "17 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|17|jam`}]},
{"title": "LOADING","rows": [{"title": "18 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|18|jam`}]},
{"title": "LOADING","rows": [{"title": "19 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|19|jam`}]},
{"title": "LOADING","rows": [{"title": "20 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|20|jam`}]},
{"title": "LOADING","rows": [{"title": "21 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|21|jam`}]},
{"title": "LOADING","rows": [{"title": "22 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|22|jam`}]},
{"title": "LOADING","rows": [{"title": "23 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|23|jam`}]},
{"title": "LOADING","rows": [{"title": "24 JAM","description": ``,"rowId": `${prefix}bugsantet ${Pe}|24|jam`}]},
],
listType: 1
}
}), { userJid: from, quoted: dev })
xdev.relayMessage(from, template.message, { messageId: template.key.id })
} else if(Pe && q.split("|")[1] === "hari" || q && q.split("|")[1] === "hari"){
let template = await generateWAMessageFromContent(from, proto.Message.fromObject({
listMessage :{
title: `SILAHKAN PILIH\n\n Name : ${pushname} ${ucapanWaktu}\n Number : ${senderNumber}\n Status : ${isOwner ? 'Owner' : 'User'}`,
description: "PILIH DI DALAM LIST",
buttonText: "CLICK DISINI",
footerText: fake,
listType: "SINGLE_SELECT",
sections: [
{"title": "LOADING","rows": [{"title": "1 HARI","description": ``,"rowId": `${prefix}bugsantet ${Pe}|1|hari`}]},
{"title": "LOADING","rows": [{"title": "2 HARI","description": ``,"rowId": `${prefix}bugsantet ${Pe}|2|hari`}]},
{"title": "LOADING","rows": [{"title": "3 HARI","description": ``,"rowId": `${prefix}bugsantet ${Pe}|3|hari`}]},
{"title": "LOADING","rows": [{"title": "4 HARI","description": ``,"rowId": `${prefix}bugsantet ${Pe}|4|hari`}]},
{"title": "LOADING","rows": [{"title": "5 HARI","description": ``,"rowId": `${prefix}bugsantet ${Pe}|5|hari`}]},
{"title": "LOADING","rows": [{"title": "6 HARI","description": ``,"rowId": `${prefix}bugsantet ${Pe}|6|hari`}]},
{"title": "LOADING","rows": [{"title": "7 HARI","description": ``,"rowId": `${prefix}bugsantet ${Pe}|7|hari`}]},
],
listType: 1
}
}), { userJid: from, quoted: dev })
xdev.relayMessage(from, template.message, { messageId: template.key.id })
}
}