module.exports = async (Araa, m, q, prefix, pushname, sender, isOwner, from, fake) => {
const Pe = q.split('|')[0].replace(new RegExp('[()+-/ +/]', 'gi'), '')
if (Pe && !q.split("|")[1] && !q.split("|")[2]){
const sections = [ {
title: `SILAHKAN PILIH`,
rows: [
{title: `DETIK`, rowId: `${prefix}santet ${Pe}|detik`},
{title: `MENIT`, rowId: `${prefix}santet ${Pe}|menit`},
{title: `JAM`, rowId: `${prefix}santet ${Pe}|jam`},
{title: `HARI`, rowId: `${prefix}santet ${Pe}|hari`},
]}]
const listMessage = { text: `Name : ${pushname}\nNumber : ${sender.split('@')[0]}\nStatus : ${isOwner ? 'Owner' : 'User'}`, mentions: [sender], footer: fake, title: `Hai Kak @${sender.split('@')[0]}`, buttonText: "Click Here", sections }
Araa.sendMessage(from, listMessage, { quoted: m })
} else if (Pe && q.split("|")[1] === 'detik' && !q.split("|")[2]) {
const sections = [ {
title: `SILAHKAN PILIH`,
rows: [
{title: `1 DETIK`, rowId: `${prefix}santet ${Pe}|1|detik`},
{title: `2 DETIK`, rowId: `${prefix}santet ${Pe}|2|detik`},
{title: `3 DETIK`, rowId: `${prefix}santet ${Pe}|3|detik`},
{title: `4 DETIK`, rowId: `${prefix}santet ${Pe}|4|detik`},
{title: `5 DETIK`, rowId: `${prefix}santet ${Pe}|5|detik`},
{title: `6 DETIK`, rowId: `${prefix}santet ${Pe}|6|detik`},
{title: `7 DETIK`, rowId: `${prefix}santet ${Pe}|7|detik`},
{title: `8 DETIK`, rowId: `${prefix}santet ${Pe}|8|detik`},
{title: `9 DETIK`, rowId: `${prefix}santet ${Pe}|9|detik`},
{title: `10 DETIK`, rowId: `${prefix}santet ${Pe}|10|detik`},
{title: `11 DETIK`, rowId: `${prefix}santet ${Pe}|11|detik`},
{title: `12 DETIK`, rowId: `${prefix}santet ${Pe}|12|detik`},
{title: `13 DETIK`, rowId: `${prefix}santet ${Pe}|13|detik`},
{title: `14 DETIK`, rowId: `${prefix}santet ${Pe}|14|detik`},
{title: `15 DETIK`, rowId: `${prefix}santet ${Pe}|15|detik`},
{title: `16 DETIK`, rowId: `${prefix}santet ${Pe}|16|detik`},
{title: `17 DETIK`, rowId: `${prefix}santet ${Pe}|17|detik`},
{title: `18 DETIK`, rowId: `${prefix}santet ${Pe}|18|detik`},
{title: `19 DETIK`, rowId: `${prefix}santet ${Pe}|19|detik`},
{title: `20 DETIK`, rowId: `${prefix}santet ${Pe}|20|detik`},
{title: `21 DETIK`, rowId: `${prefix}santet ${Pe}|21|detik`},
{title: `22 DETIK`, rowId: `${prefix}santet ${Pe}|22|detik`},
{title: `23 DETIK`, rowId: `${prefix}santet ${Pe}|23|detik`},
{title: `24 DETIK`, rowId: `${prefix}santet ${Pe}|24|detik`},
{title: `25 DETIK`, rowId: `${prefix}santet ${Pe}|25|detik`},
{title: `26 DETIK`, rowId: `${prefix}santet ${Pe}|26|detik`},
{title: `27 DETIK`, rowId: `${prefix}santet ${Pe}|27|detik`},
{title: `28 DETIK`, rowId: `${prefix}santet ${Pe}|28|detik`},
{title: `29 DETIK`, rowId: `${prefix}santet ${Pe}|29|detik`},
{title: `30 DETIK`, rowId: `${prefix}santet ${Pe}|30|detik`},
{title: `31 DETIK`, rowId: `${prefix}santet ${Pe}|31|detik`},
{title: `32 DETIK`, rowId: `${prefix}santet ${Pe}|32|detik`},
{title: `33 DETIK`, rowId: `${prefix}santet ${Pe}|33|detik`},
{title: `34 DETIK`, rowId: `${prefix}santet ${Pe}|34|detik`},
{title: `35 DETIK`, rowId: `${prefix}santet ${Pe}|35|detik`},
{title: `36 DETIK`, rowId: `${prefix}santet ${Pe}|36|detik`},
{title: `37 DETIK`, rowId: `${prefix}santet ${Pe}|37|detik`},
{title: `38 DETIK`, rowId: `${prefix}santet ${Pe}|38|detik`},
{title: `39 DETIK`, rowId: `${prefix}santet ${Pe}|39|detik`},
{title: `40 DETIK`, rowId: `${prefix}santet ${Pe}|40|detik`},
{title: `41 DETIK`, rowId: `${prefix}santet ${Pe}|41|detik`},
{title: `42 DETIK`, rowId: `${prefix}santet ${Pe}|42|detik`},
{title: `43 DETIK`, rowId: `${prefix}santet ${Pe}|43|detik`},
{title: `44 DETIK`, rowId: `${prefix}santet ${Pe}|44|detik`},
{title: `45 DETIK`, rowId: `${prefix}santet ${Pe}|45|detik`},
{title: `46 DETIK`, rowId: `${prefix}santet ${Pe}|46|detik`},
{title: `47 DETIK`, rowId: `${prefix}santet ${Pe}|47|detik`},
{title: `48 DETIK`, rowId: `${prefix}santet ${Pe}|48|detik`},
{title: `49 DETIK`, rowId: `${prefix}santet ${Pe}|49|detik`},
{title: `50 DETIK`, rowId: `${prefix}santet ${Pe}|50|detik`},
{title: `51 DETIK`, rowId: `${prefix}santet ${Pe}|51|detik`},
{title: `52 DETIK`, rowId: `${prefix}santet ${Pe}|52|detik`},
{title: `53 DETIK`, rowId: `${prefix}santet ${Pe}|53|detik`},
{title: `54 DETIK`, rowId: `${prefix}santet ${Pe}|54|detik`},
{title: `55 DETIK`, rowId: `${prefix}santet ${Pe}|55|detik`},
{title: `56 DETIK`, rowId: `${prefix}santet ${Pe}|56|detik`},
{title: `57 DETIK`, rowId: `${prefix}santet ${Pe}|57|detik`},
{title: `58 DETIK`, rowId: `${prefix}santet ${Pe}|58|detik`},
{title: `59 DETIK`, rowId: `${prefix}santet ${Pe}|59|detik`},
{title: `60 DETIK`, rowId: `${prefix}santet ${Pe}|60|detik`},
]}]
const listMessage = { text: `Name : ${pushname}\nNumber : ${sender.split('@')[0]}\nStatus : ${isOwner ? 'Owner' : 'User'}`, mentions: [sender], footer: fake, title: `Hai Kak @${sender.split('@')[0]}`, buttonText: "Click Here", sections }
Araa.sendMessage(from, listMessage, { quoted: m })
} else if (Pe && q.split("|")[1] === 'menit' && !q.split("|")[2]) {
const sections = [ {
title: `SILAHKAN PILIH`,
rows: [
{title: `1 MENIT`, rowId: `${prefix}santet ${Pe}|1|menit`},
{title: `2 MENIT`, rowId: `${prefix}santet ${Pe}|2|menit`},
{title: `3 MENIT`, rowId: `${prefix}santet ${Pe}|3|menit`},
{title: `4 MENIT`, rowId: `${prefix}santet ${Pe}|4|menit`},
{title: `5 MENIT`, rowId: `${prefix}santet ${Pe}|5|menit`},
{title: `6 MENIT`, rowId: `${prefix}santet ${Pe}|6|menit`},
{title: `7 MENIT`, rowId: `${prefix}santet ${Pe}|7|menit`},
{title: `8 MENIT`, rowId: `${prefix}santet ${Pe}|8|menit`},
{title: `9 MENIT`, rowId: `${prefix}santet ${Pe}|9|menit`},
{title: `10 MENIT`, rowId: `${prefix}santet ${Pe}|10|menit`},
{title: `11 MENIT`, rowId: `${prefix}santet ${Pe}|11|menit`},
{title: `12 MENIT`, rowId: `${prefix}santet ${Pe}|12|menit`},
{title: `13 MENIT`, rowId: `${prefix}santet ${Pe}|13|menit`},
{title: `14 MENIT`, rowId: `${prefix}santet ${Pe}|14|menit`},
{title: `15 MENIT`, rowId: `${prefix}santet ${Pe}|15|menit`},
{title: `16 MENIT`, rowId: `${prefix}santet ${Pe}|16|menit`},
{title: `17 MENIT`, rowId: `${prefix}santet ${Pe}|17|menit`},
{title: `18 MENIT`, rowId: `${prefix}santet ${Pe}|18|menit`},
{title: `19 MENIT`, rowId: `${prefix}santet ${Pe}|19|menit`},
{title: `20 MENIT`, rowId: `${prefix}santet ${Pe}|20|menit`},
{title: `21 MENIT`, rowId: `${prefix}santet ${Pe}|21|menit`},
{title: `22 MENIT`, rowId: `${prefix}santet ${Pe}|22|menit`},
{title: `23 MENIT`, rowId: `${prefix}santet ${Pe}|23|menit`},
{title: `24 MENIT`, rowId: `${prefix}santet ${Pe}|24|menit`},
{title: `25 MENIT`, rowId: `${prefix}santet ${Pe}|25|menit`},
{title: `26 MENIT`, rowId: `${prefix}santet ${Pe}|26|menit`},
{title: `27 MENIT`, rowId: `${prefix}santet ${Pe}|27|menit`},
{title: `28 MENIT`, rowId: `${prefix}santet ${Pe}|28|menit`},
{title: `29 MENIT`, rowId: `${prefix}santet ${Pe}|29|menit`},
{title: `30 MENIT`, rowId: `${prefix}santet ${Pe}|30|menit`},
{title: `31 MENIT`, rowId: `${prefix}santet ${Pe}|31|menit`},
{title: `32 MENIT`, rowId: `${prefix}santet ${Pe}|32|menit`},
{title: `33 MENIT`, rowId: `${prefix}santet ${Pe}|33|menit`},
{title: `34 MENIT`, rowId: `${prefix}santet ${Pe}|34|menit`},
{title: `35 MENIT`, rowId: `${prefix}santet ${Pe}|35|menit`},
{title: `36 MENIT`, rowId: `${prefix}santet ${Pe}|36|menit`},
{title: `37 MENIT`, rowId: `${prefix}santet ${Pe}|37|menit`},
{title: `38 MENIT`, rowId: `${prefix}santet ${Pe}|38|menit`},
{title: `39 MENIT`, rowId: `${prefix}santet ${Pe}|39|menit`},
{title: `40 MENIT`, rowId: `${prefix}santet ${Pe}|40|menit`},
{title: `41 MENIT`, rowId: `${prefix}santet ${Pe}|41|menit`},
{title: `42 MENIT`, rowId: `${prefix}santet ${Pe}|42|menit`},
{title: `43 MENIT`, rowId: `${prefix}santet ${Pe}|43|menit`},
{title: `44 MENIT`, rowId: `${prefix}santet ${Pe}|44|menit`},
{title: `45 MENIT`, rowId: `${prefix}santet ${Pe}|45|menit`},
{title: `46 MENIT`, rowId: `${prefix}santet ${Pe}|46|menit`},
{title: `47 MENIT`, rowId: `${prefix}santet ${Pe}|47|menit`},
{title: `48 MENIT`, rowId: `${prefix}santet ${Pe}|48|menit`},
{title: `49 MENIT`, rowId: `${prefix}santet ${Pe}|49|menit`},
{title: `50 MENIT`, rowId: `${prefix}santet ${Pe}|50|menit`},
{title: `51 MENIT`, rowId: `${prefix}santet ${Pe}|51|menit`},
{title: `52 MENIT`, rowId: `${prefix}santet ${Pe}|52|menit`},
{title: `53 MENIT`, rowId: `${prefix}santet ${Pe}|53|menit`},
{title: `54 MENIT`, rowId: `${prefix}santet ${Pe}|54|menit`},
{title: `55 MENIT`, rowId: `${prefix}santet ${Pe}|55|menit`},
{title: `56 MENIT`, rowId: `${prefix}santet ${Pe}|56|menit`},
{title: `57 MENIT`, rowId: `${prefix}santet ${Pe}|57|menit`},
{title: `58 MENIT`, rowId: `${prefix}santet ${Pe}|58|menit`},
{title: `59 MENIT`, rowId: `${prefix}santet ${Pe}|59|menit`},
{title: `60 MENIT`, rowId: `${prefix}santet ${Pe}|60|menit`},
]}]
const listMessage = { text: `Name : ${pushname}\nNumber : ${sender.split('@')[0]}\nStatus : ${isOwner ? 'Owner' : 'User'}`, mentions: [sender], footer: fake, title: `Hai Kak @${sender.split('@')[0]}`, buttonText: "Click Here", sections }
Araa.sendMessage(from, listMessage, { quoted: m })
} else if (Pe && q.split("|")[1] === 'jam' && !q.split("|")[2]) {
const sections = [ {
title: `SILAHKAN PILIH`,
rows: [
{title: `1 JAM`, rowId: `${prefix}santet ${Pe}|1|jam`},
{title: `2 JAM`, rowId: `${prefix}santet ${Pe}|2|jam`},
{title: `3 JAM`, rowId: `${prefix}santet ${Pe}|3|jam`},
{title: `4 JAM`, rowId: `${prefix}santet ${Pe}|4|jam`},
{title: `5 JAM`, rowId: `${prefix}santet ${Pe}|5|jam`},
{title: `6 JAM`, rowId: `${prefix}santet ${Pe}|6|jam`},
{title: `7 JAM`, rowId: `${prefix}santet ${Pe}|7|jam`},
{title: `8 JAM`, rowId: `${prefix}santet ${Pe}|8|jam`},
{title: `9 JAM`, rowId: `${prefix}santet ${Pe}|9|jam`},
{title: `10 JAM`, rowId: `${prefix}santet ${Pe}|10|jam`},
{title: `11 JAM`, rowId: `${prefix}santet ${Pe}|11|jam`},
{title: `12 JAM`, rowId: `${prefix}santet ${Pe}|12|jam`},
{title: `13 JAM`, rowId: `${prefix}santet ${Pe}|13|jam`},
{title: `14 JAM`, rowId: `${prefix}santet ${Pe}|14|jam`},
{title: `15 JAM`, rowId: `${prefix}santet ${Pe}|15|jam`},
{title: `16 JAM`, rowId: `${prefix}santet ${Pe}|16|jam`},
{title: `17 JAM`, rowId: `${prefix}santet ${Pe}|17|jam`},
{title: `18 JAM`, rowId: `${prefix}santet ${Pe}|18|jam`},
{title: `19 JAM`, rowId: `${prefix}santet ${Pe}|19|jam`},
{title: `20 JAM`, rowId: `${prefix}santet ${Pe}|20|jam`},
{title: `21 JAM`, rowId: `${prefix}santet ${Pe}|21|jam`},
{title: `22 JAM`, rowId: `${prefix}santet ${Pe}|22|jam`},
{title: `23 JAM`, rowId: `${prefix}santet ${Pe}|23|jam`},
{title: `24 JAM`, rowId: `${prefix}santet ${Pe}|24|jam`},
]}]
const listMessage = { text: `Name : ${pushname}\nNumber : ${sender.split('@')[0]}\nStatus : ${isOwner ? 'Owner' : 'User'}`, mentions: [sender], footer: fake, title: `Hai Kak @${sender.split('@')[0]}`, buttonText: "Click Here", sections }
Araa.sendMessage(from, listMessage, { quoted: m })
} else if (Pe && q.split("|")[1] === 'hari' && !q.split("|")[2]) {
const sections = [ {
title: `SILAHKAN PILIH`,
rows: [
{title: `1 HARI`, rowId: `${prefix}santet ${Pe}|1|hari`},
{title: `2 HARI`, rowId: `${prefix}santet ${Pe}|2|hari`},
{title: `3 HARI`, rowId: `${prefix}santet ${Pe}|3|hari`},
{title: `4 HARI`, rowId: `${prefix}santet ${Pe}|4|hari`},
{title: `5 HARI`, rowId: `${prefix}santet ${Pe}|5|hari`},
{title: `6 HARI`, rowId: `${prefix}santet ${Pe}|6|hari`},
{title: `7 HARI`, rowId: `${prefix}santet ${Pe}|7|hari`},
]}]
const listMessage = { text: `Name : ${pushname}\nNumber : ${sender.split('@')[0]}\nStatus : ${isOwner ? 'Owner' : 'User'}`, mentions: [sender], footer: fake, title: `Hai Kak @${sender.split('@')[0]}`, buttonText: "Click Here", sections }
Araa.sendMessage(from, listMessage, { quoted: m })
}
}